version: '3.7'
services:

  kafka:
    image: debezium/kafka:1.7
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      CLUSTER_ID: 5Yr1SIgYQz-b-dgRabWx4g
      BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      CREATE_TOPICS: "sa:1:1,businesses:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - integration-test

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    networks:
      - integration-test
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: broker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 5s
      retries: 5

  integration-tests:
    build:
      context: integration-test
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - postgres
    networks:
      - integration-test

volumes:
  postgres_data:
    driver: local
  kafka_data:
    driver: local

networks:
  integration-test:
    driver: bridge