version: '3.3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    container_name: elasticsearch
    networks:
      - integration-test
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - sales-database:/usr/share/elasticsearch/data
    healthcheck:
      test: "curl -f elasticsearch:9200/_cluster/health?wait_for_status=green&timeout=25s || exit 1"
      interval: 1s
      timeout: 1s
      retries: 10

  sales:
    container_name: sales
    build:
      context: sales
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - elasticsearch
    networks:
      - integration-test
    healthcheck:
      test: "curl -f http://sales:8082/actuator/health"
      interval: 1s
      timeout: 1s
      retries: 10

  integration-tests:
    container_name: integration-test
    build:
      context: integration-test
      dockerfile: Dockerfile
    depends_on:
      - sales
      - elasticsearch
    networks:
      - integration-test

volumes:
  sales-database:
    driver: local

networks:
  integration-test:
    driver: bridge