version: '2.3'
services:

  sales:
    container_name: sales
    build:
      context: sales
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - integration-test
    healthcheck:
      test: "curl -f http://sales:8082/actuator/health"
      retries: 10
      interval: 1s
      start_period: 2s

  integration-tests:
    container_name: integration-test
    build:
      context: integration-test
      dockerfile: Dockerfile
    depends_on:
      sales:
        condition: service_healthy
    networks:
      - integration-test

volumes:
  postgres_data:
    driver: local
  kafka_data:
    driver: local

networks:
  integration-test:
    driver: bridge