server:
  port: 8082
  error:
    include-message: always
    include-stacktrace: on_param
    include-binding-errors: always

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  main:
    allow-circular-references: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: yyyy-MM-dd'T'HH:mm

  elasticsearch:
    uris: ${ELASTICSEARCH_HOST}

  kafka:
    listener:
      ack-mode: record
      concurrency: 1
    producer:
      key-serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer