server:
  port: 8082
  error:
    include-message: always
    include-stacktrace: on_param
    include-binding-errors: always

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: yyyy-MM-dd'T'HH:mm

  elasticsearch:
    uris: "http://localhost:9200"